name: Build gbarunner3
on: push
jobs:
  Windows:
    runs-on: windows-latest
    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITARM: /opt/devkitpro/devkitARM
      DEVKITPPC: /opt/devkitpro/devkitPPC
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MSYS
        install: >-
            base-devel
    - name: Setup dkp msys
      run: |
        pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
        pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
        wget https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
        pacman --noconfirm -U devkitpro-keyring.pkg.tar.xz
        rm devkitpro-keyring.pkg.tar.xz
        echo '[dkp-libs]' >> /etc/pacman.conf
        echo 'Server = http://downloads.devkitpro.org/packages' >> /etc/pacman.conf
        echo '[dkp-windows]' >> /etc/pacman.conf
        echo 'Server = http://downloads.devkitpro.org/packages/windows' >> /etc/pacman.conf
        echo 'export PATH=${DEVKITPRO}/tools/bin:$PATH' >> /etc/profile.d/devkit-path.sh
        pacman --noconfirm -Syu
        pacman --noconfirm -S nds-dev
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build
      run: |
        make -Ccode
    - name: Prepare asset
      run: |
        mkdir -p assets
        cp "code/bootstrap/bootstrap.nds" "assets/GbaRunner3-${GITHUB_REF##*/}.nds"
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        overwrite: true
        file_glob: true
        tag: |
          builds
        file: |
          assets/*